name: THOR
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - cudatoolkit=10.0.130=0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - mkl=2019.4=243
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1c=h7b6447c_1
  - pillow=6.0.0=py37h34e0f95_0
  - pip=19.1.1=py37_0
  - pycparser=2.19=py37_0
  - python=3.7.3=h0371630_0
  - pytorch=1.1.0=py3.7_cuda10.0.130_cudnn7.5.1_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.3.0=py37_cu10.0.130_1
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - backcall==0.1.0
    - colorama==0.4.1
    - cycler==0.10.0
    - cython==0.29.10
    - decorator==4.4.0
    - fire==0.1.3
    - got10k==0.1.3
    - ipdb==0.12
    - ipython==7.5.0
    - ipython-genutils==0.2.0
    - jedi==0.13.3
    - kiwisolver==1.1.0
    - llvmlite==0.29.0
    - matplotlib==3.1.0
    - numba==0.44.0
    - opencv-python==4.1.0.25
    - oxuva==0.0.1
    - pandas==0.24.2
    - parso==0.4.0
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - pygments==2.4.2
    - pyparsing==2.4.0
    - python-dateutil==2.8.0
    - pytz==2019.1
    - scipy==1.3.0
    - shapely==1.6.4.post2
    - tqdm==4.32.1
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - wget==3.2
    - yacs==0.1.6
prefix: ~/anaconda3/envs/THOR
